### ISSUE TITLE
Add license to allow this module to be installed in the private repository 

### ISSUE THREAD

**Issue by dilipkumar2k6** [vacuumlabs/react-validation#17]
We want to use this module and to do that we need to install this module in our private repo. Which needs license copy to meet the legal requirement. 

We prefer to have MIT license :-). Following is one example.
https://github.com/xolvio/chimp/blob/master/LICENSE.md

Thanks,
Dilip

**Comment by marcelka** [comment]
Dear Dilip,

Thanks for pointing this out. I have added MIT license.

FYI: If you are just starting to use the library just now, I recommend waiting for few days until a newer version (with incompatible API) is published. The new version will have better features and more detailed documentation. (It is almost ready in branch change-api.)

**Comment by dilipkumar2k6** [comment]
Thanks Marcela. I do see License file however I forgot to mention that you will need to modify package.json as well. Following change is required.
`"license": "MIT"`

You can refer  https://github.com/xolvio/chimp/blob/master/package.json

**Comment by marcelka** [comment]
Done. I hope it is all right now :) Please let me know if you have any other requests!
