### ISSUE TITLE
Can we have tests?

### ISSUE THREAD

**Issue by andela-osule** [vacuumlabs/react-validation#19]
This is an excellent validation library! However, are there plans toward backfilling tests? I'll be happy to contribute towards making that happen.

**Comment by marcelka** [comment]
Thanks, I am glad that you like the library. I am not sure what you mean by backfilling tests. If you mean adding some tests, I would like that! However, I would like to ask you to only test the exposed public functions (API). I do not want unit tests or any other tests of internal library parts, as the troubles to maintain these kinds of tests usually outweigh the benefits.

**Comment by marcelka** [comment]
Hi, I am closing this issue due to your long inactivity.
