### ISSUE TITLE
Don't require the user to have gulp installed globally

### ISSUE THREAD

**Issue by dwayne** [vacuumlabs/react-validation#22]
Adding

```json
"scripts": {
    "gulp": "gulp"
},
```

to `package.json` would make it so that you can simply type `npm run gulp <whatever>` without having to install gulp globally with `npm i -g gulp`.

**Comment by marcelka** [comment]
Dwayne,
Thanks for your suggestion! I have just published new version that contains this change.

Btw, global gulp just runs your local gulp, if it is present in you project. So it would result in the same gulp being called, you would just need to have installed global gulp (of any version).
