### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by michalvalasek** [vacuumlabs/react-validation#8]
Would it be possible to add some docs to the Readme file? Maybe an extract from @marcelka's talk on Reactive2015 would be a great start.

**Comment by marcelka** [comment]
I added examples from the talk, I hope it helps for the start. You can also check out example1/App.jsx, it might help a lot. Complete and more detailed documentation will come soon.

**Comment by michalvalasek** [comment]
Cool, thanks!

**Comment by sapegin** [comment]
The readme says “it will be finished soon”. Any plans to add more docs *soon*?

**Comment by mc2** [comment]
More documentation please!

Having issues with implementation of `showValidation` 

It seems that `Validate.js`, lines 337, and 341, that the passed `props.onValidation` is called separately for `validationResult` and `showValidation`.  That took a while to figure out and write a correct validation handler to expect calls where at least one of these values is `undefined`.

Thanks!

**Comment by marcelka** [comment]
@mc2 Yes, you are correct, `props.onValidation` is called separately for `validationResult` and `showValidation`. I am sorry for your trouble with the library.

The readme far from complete at the moment; however, going through this [example] (https://github.com/vacuumlabs/validation/blob/master/example1/App.jsx) should help a lot, it pretty much covers everything important.

**Comment by marcelka** [comment]
@sapegin I am not completely happy with the library as it is now (specifically, the showValidation-hinting does not work well for multiple-field validations). Fixing this will result in slight API change, so I plan to add detailed documentation afterwards. The fix should be available in 1-2 weeks from now; and the documentation in another week or so.

**Comment by protactinium** [comment]
@marcelka, I have started using your validation project and I like it. It has a great potential and I have actually came around few issues that were somehow easy to solve. But, I am not sure if it is going to be maintained. Is there a plan to make it production-ready ?

**Comment by VyvIT** [comment]
@marcelka, Any news on this? Or have you found something more promising for validation?

**Comment by marcelka** [comment]
@protactinium Yes, I plan to resume working on this project in very near future. I plan to fix all the issues that I know of. If you have any feedback/suggestions, let me please know. Thanks!

**Comment by marcelka** [comment]
The documentation is finished, along with a new version of the library that provides much better show-validation data.
